min_version = "2025.11.8"

[tools]
1password-cli = "latest"
btop = "1.4.4"
chezmoi = "latest"
doggo = "1.0.5"
fastfetch = "2.57.1"
fzf = "0.67.0"
github-cli = "2.82.1"
lsd = "1.2.0"
neovim = "0.11.5"
node = "24.13.0"
opencode = "1.1.8"
ripgrep = "14.1.1"
ruby = "4.0.1"
starship = "1.23.0"
zellij = "0.43.0"
zoxide = "0.9.8"

[settings]
lockfile = true
pin = true
