min_version = "2025.11.8"

[tools]
# Lang
go   = "1.25.6"
node = "24.13.0"
ruby = "4.0.1"

# Util
bat           = "latest"
delta         = "latest"
direnv        = "latest"
1password-cli = "latest"
chezmoi       = "latest"
doggo         = "1.0.5"
fastfetch     = "2.57.1"
fd            = "latest"
fzf           = "0.67.0"
github-cli    = "2.82.1"
glow          = "latest"
jq            = "latest"
lsd           = "1.2.0"
neovim        = "0.11.5"
opencode      = "1.1.8"
pnpm          = "latest"
ripgrep       = "14.1.1"
starship      = "1.23.0"
tmux          = "latest"
usage         = "latest"
zellij        = "0.43.0"
zoxide        = "0.9.8"

[settings]
lockfile = true
pin = true
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]
